<?php return array (
  'siteName' => '小策一喋 - 专注WEB开发及系统运维技术！',
  'keyword' => '前端设计,后端开发,系统运维',
  'description' => '小策一喋 - 专注WEB开发及系统运维技术：前端设计、后端开发、系统运维',
  'tel' => '57968663',
  'mobilephone' => '18588220078',
  'fax' => '57968663',
  'email' => 'xvpindex@qq.com',
  'qq' => '470701948',
  'address' => '深圳市南山区创业路中兴工业城13栋109室',
  'postcode' => '518054',
  '' => '',
  'counter' => '<script language="javascript" type="text/javascript" src="http://js.users.51.la/7242161.js"></script>
<noscript><a href="http://www.51.la/?7242161" target="_blank"><img alt="我要啦免费统计" src="http://img.users.51.la/7242161.asp" style="border:none" /></a></noscript>',
  'smtp_host' => 'smtp.sina.com',
  'smtp_port' => '22',
  'from_email' => 'xvpindex@sina.com123123',
  'from_name' => '赵峡策',
  'smtp_user' => 'xvpindex',
  'smtp_pass' => '123456',
  'reply_email' => 'xvpindex@qq.com',
  'reply_name' => '赵峡策',
  'test_email' => '331273345@qq.com',
  'subSummaryLen' => '300',
  'summaryHtmlTags' => '',
  'autoLoginDuration' => '604800',
  'theme' => 'eblog',
  'enable_lazyload_img' => '1',
  'post_list_show_topic_icon' => '0',
  'user_required_admin_verfiy' => '1',
  'user_required_email_verfiy' => '0',
  'post_list_type' => '0',
  'auto_remote_image_local' => '0',
  'mobile_post_list_page_count' => '8',
  'mobileSummaryHtmlTags' => '',
  'TOKEN' => 
  array (
    'admin_marked' => 'xvpindex@qq.com',
    'admin_timeout' => 3600,
    'member_marked' => 'http://www.topstack.cn',
    'member_timeout' => 3600,
  ),
);